In [5]:
import duckdb

# Replace the path below with whatever "Copy Relative Path" pasted!
duckdb.sql("SELECT * FROM '202603-citibike-tripdata/202603-citibike-tripdata_1.csv' LIMIT 5").df()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,A324B30D9C1F6CFE,electric_bike,2026-03-11 18:50:05.658,2026-03-11 19:02:07.383,Monroe St & Bedford Ave,4368.05,Jefferson Ave & Patchen Ave,4375.02,40.685144,-73.953809,40.686090,-73.926280,member
1,4D0D692F5FE64064,electric_bike,2026-03-08 17:39:18.215,2026-03-08 17:54:17.959,East End Ave & E 86 St,7113.08,E 77 St & 1 Ave,7020.02,40.775186,-73.944461,40.770956,-73.953562,member
2,2BEE12E018E094A5,electric_bike,2026-03-06 12:37:33.174,2026-03-06 13:03:23.951,Washington Pl & Broadway,5755.01,7 St & 3 Ave,3996.01,40.729039,-73.994046,40.672603,-73.989830,member
3,7800A32885CD2D67,electric_bike,2026-03-09 22:48:26.091,2026-03-09 23:02:24.085,Kent Ave & Grand St,5388.01,Henry St & Middagh St,4861.05,40.716425,-73.965940,40.700300,-73.991581,member
4,56D7FEABCE16E004,electric_bike,2026-03-07 13:37:15.215,2026-03-07 13:57:59.731,Monroe St & Bedford Ave,4368.05,7 St & 3 Ave,3996.01,40.685144,-73.953809,40.672603,-73.989830,member

In [6]:
import os

# Print all files and folders right next to this notebook
print(os.listdir('.'))

['week1_analysis.ipynb', '202603-citibike-tripdata.zip', '.DS_Store', 'projects', '202603-citibike-tripdata']

In [17]:
import duckdb
file_path='202603-citibike-tripdata/202603-citibike-tripdata_1.csv'

query= f"""
SELECT 
    count(*) AS total_rows,
    MIN(started_at) AS earliest_start,
    MAX(ended_at) AS latest_end,
    COUNT(DISTINCT rideable_type) AS bike_types
FROM read_csv_auto('{file_path}')
"""

duckdb.sql(query).df()

   total_rows          earliest_start              latest_end  bike_types
0     1000000 2026-02-28 06:05:20.166 2026-03-15 19:47:10.511           2

In [22]:
import duckdb
file_path='202603-citibike-tripdata/202603-citibike-tripdata_1.csv'
query= f"""
SELECT
     COUNT(*)-COUNT(start_station_name) AS missing_start_stations,
     COUNT(*)-COUNT(end_station_name) AS missing_end_stations
FROM read_csv_auto('{file_path}')
"""
duckdb.sql(query).df()

   missing_start_stations  missing_end_stations
0                     576                  2312

In [27]:
import duckdb
file_path = '202603-citibike-tripdata/202603-citibike-tripdata_1.csv'

query = f"""
SELECT
   start_station_name,
   COUNT(*) AS trip_count
FROM read_csv_auto('{file_path}')
WHERE start_station_name IS NOT NULL
GROUP BY start_station_name
ORDER BY trip_count DESC
LIMIT 10
"""
duckdb.sql(query).df()

         start_station_name  trip_count
0  Pier 61 at Chelsea Piers        3895
1           W 21 St & 6 Ave        3840
2     Lafayette St & E 8 St        3288
3        E 17 St & Broadway        3011
4           6 Ave & W 33 St        3003
5           9 Ave & W 33 St        2970
6   University Pl & E 14 St        2949
7        Broadway & W 58 St        2937
8           W 31 St & 7 Ave        2929
9        Broadway & W 25 St        2922

In [30]:
import duckdb
file_path = '202603-citibike-tripdata/202603-citibike-tripdata_1.csv'

query = f"""
SELECT
  end_station_name,
  count(*) AS trip_count
FROM read_csv_auto('{file_path}')
WHERE end_station_name IS NOT NULL
GROUP BY end_station_name
ORDER BY trip_count DESC
LIMIT 10
"""
duckdb.sql(query).df()

           end_station_name  trip_count
0           W 21 St & 6 Ave        4599
1  Pier 61 at Chelsea Piers        4303
2     Lafayette St & E 8 St        3885
3           9 Ave & W 33 St        3556
4        Broadway & W 25 St        3536
5     Clinton St & Grand St        3047
6  Cleveland Pl & Spring St        2977
7        Park Ave & E 42 St        2946
8        Broadway & E 21 St        2939
9          W 43 St & 10 Ave        2890

In [31]:
import duckdb
file_path = '202603-citibike-tripdata/202603-citibike-tripdata_1.csv'

query = f"""
SELECT 
    HOUR(started_at) AS hour_of_day,
    COUNT(*) AS total_trips
FROM read_csv_auto('{file_path}')
GROUP BY hour_of_day
ORDER BY total_trips DESC
"""

duckdb.sql(query).df()

    hour_of_day  total_trips
0            17       101289
1            18        92109
2            16        78976
3            15        71398
4             8        65940
5            19        64826
6            14        63203
7            13        56229
8             9        51438
9            12        51121
10           11        45319
11            7        44442
12           10        41291
13           20        40993
14           21        30373
15           22        22916
16            6        22271
17           23        16523
18            0        11349
19            5         8918
20            1         7196
21            4         4139
22            2         4003
23            3         3738

In [32]:
import duckdb
file_path = '202603-citibike-tripdata/202603-citibike-tripdata_1.csv'

query = f"""
SELECT 
    DAYNAME(started_at) AS day_of_week,
    HOUR(started_at) AS hour_of_day,
    COUNT(*) AS total_trips
FROM read_csv_auto('{file_path}')
GROUP BY day_of_week, hour_of_day
ORDER BY total_trips DESC
LIMIT 10
"""

duckdb.sql(query).df()

  day_of_week  hour_of_day  total_trips
0   Wednesday           17        20473
1      Monday           17        18536
2   Wednesday           18        18003
3     Tuesday           17        17735
4      Monday           18        17106
5     Tuesday           18        17074
6   Wednesday            8        15672
7     Tuesday            8        14867
8   Wednesday           16        13947
9      Friday           17        13395

In [33]:
import duckdb
file_path = '202603-citibike-tripdata/202603-citibike-tripdata_1.csv'

query = f"""
SELECT 
    HOUR(started_at) AS hour_of_day,
    COUNT(*) AS total_trips
FROM read_csv_auto('{file_path}')
WHERE HOUR(started_at) BETWEEN 6 AND 11
GROUP BY hour_of_day
ORDER BY total_trips DESC
LIMIT 1
"""

duckdb.sql(query).df()

   hour_of_day  total_trips
0            8        65940

In [34]:
import duckdb
file_path = '202603-citibike-tripdata/202603-citibike-tripdata_1.csv'

query = f"""
SELECT 
    HOUR(started_at) AS hour_of_day,
    COUNT(*) AS total_trips
FROM read_csv_auto('{file_path}')
WHERE HOUR(started_at) BETWEEN 16 AND 19
GROUP BY hour_of_day
ORDER BY total_trips DESC
LIMIT 1
"""

duckdb.sql(query).df()

   hour_of_day  total_trips
0           17       101289

In [35]:
import duckdb
file_path = '202603-citibike-tripdata/202603-citibike-tripdata_1.csv'

query = f"""
SELECT 
    CASE 
        WHEN HOUR(started_at) BETWEEN 6 AND 11 THEN 'Morning (6am-11am)'
        WHEN HOUR(started_at) BETWEEN 12 AND 17 THEN 'Afternoon/Evening (12pm-5pm)'
        ELSE 'Night (6pm-5am)'
    END AS time_window,
    HOUR(started_at) AS hour_of_day,
    COUNT(*) AS total_trips
FROM read_csv_auto('{file_path}')
GROUP BY time_window, hour_of_day
ORDER BY time_window, total_trips DESC
"""

duckdb.sql(query).df()

                     time_window  hour_of_day  total_trips
0   Afternoon/Evening (12pm-5pm)           17       101289
1   Afternoon/Evening (12pm-5pm)           16        78976
2   Afternoon/Evening (12pm-5pm)           15        71398
3   Afternoon/Evening (12pm-5pm)           14        63203
4   Afternoon/Evening (12pm-5pm)           13        56229
5   Afternoon/Evening (12pm-5pm)           12        51121
6             Morning (6am-11am)            8        65940
7             Morning (6am-11am)            9        51438
8             Morning (6am-11am)           11        45319
9             Morning (6am-11am)            7        44442
10            Morning (6am-11am)           10        41291
11            Morning (6am-11am)            6        22271
12               Night (6pm-5am)           18        92109
13               Night (6pm-5am)           19        64826
14               Night (6pm-5am)           20        40993
15               Night (6pm-5am)           21        30373
16               Night (6pm-5am)           22        22916
17               Night (6pm-5am)           23        16523
18               Night (6pm-5am)            0        11349
19               Night (6pm-5am)            5         8918
20               Night (6pm-5am)            1         7196
21               Night (6pm-5am)            4         4139
22               Night (6pm-5am)            2         4003
23               Night (6pm-5am)            3         3738

In [38]:
import duckdb
file_path = '202603-citibike-tripdata/202603-citibike-tripdata_1.csv'

query = f"""
WITH hourly_counts AS (
    SELECT 
        CASE 
            WHEN HOUR(started_at) BETWEEN 6 AND 11 THEN 'Morning (6am-11am)'
            WHEN HOUR(started_at) BETWEEN 12 AND 17 THEN 'Afternoon/Evening (12pm-5pm)'
            ELSE 'Night (6pm-5am)'
        END AS time_window,
        HOUR(started_at) AS hour_of_day,
        COUNT(*) AS total_trips
    FROM read_csv_auto('{file_path}')
    GROUP BY time_window, hour_of_day
)
SELECT 
    time_window,
    MAX_BY(hour_of_day, total_trips) AS peak_hour,
    MAX(total_trips) AS peak_trips
FROM hourly_counts
GROUP BY time_window
ORDER BY time_window
"""

duckdb.sql(query).df()

                    time_window  peak_hour  peak_trips
0  Afternoon/Evening (12pm-5pm)         17      101289
1            Morning (6am-11am)          8       65940
2               Night (6pm-5am)         18       92109

In [39]:
import duckdb
file_path = '202603-citibike-tripdata/202603-citibike-tripdata_1.csv'

query = f"""
SELECT
  member_casual,
  COUNT(*) AS total_trips
FROM read_csv_auto('{file_path}')
GROUP BY member_casual
"""
duckdb.sql(query).df()

  member_casual  total_trips
0        member       866993
1        casual       133007

In [40]:
import duckdb
file_path = '202603-citibike-tripdata/202603-citibike-tripdata_1.csv'

query = f"""
SELECT 
    member_casual,
    COUNT(*) AS total_trips,
    ROUND(AVG(DATE_DIFF('minute', started_at, ended_at)), 2) AS avg_duration_mins
FROM read_csv_auto('{file_path}')
GROUP BY member_casual
"""

duckdb.sql(query).df()

  member_casual  total_trips  avg_duration_mins
0        member       866993              11.13
1        casual       133007              20.43

In [43]:
import duckdb

query = """
SELECT COUNT(*) AS total_trips
FROM read_csv_auto('202603-citibike-tripdata/*.csv')
"""

duckdb.sql(query).df()

   total_trips
0      2945753